data:
  batch_size: 32
  buffer_size: 10000
  validation_split: 0.2
logging:
  checkpoint_dir: checkpoints
  log_dir: logs
  save_freq: 1
model:
  decoder_filters: null
  encoder_filters:
  - 32
  - 64
  - 64
  - 64
  input_shape:
  - 64
  - 64
  - 3
  latent_dim: 128
training:
  early_stopping_patience: 3
  epochs: 5
  learning_rate: 0.0001
